import { createFileRoute, Link } from "@tanstack/react-router";
import { HomeLayout } from "fumadocs-ui/layouts/home";
import {
  ArrowRight,
  BadgeCheck,
  BookOpen,
  Bot,
  ClipboardCheck,
  Code2,
  CookingPot,
  FileCode2,
  FileText,
  GitBranch,
  GitPullRequest,
  KeyRound,
  Library,
  ListChecks,
  LockKeyhole,
  type LucideIcon,
  MessageSquareText,
  Rocket,
  ShieldCheck,
  Terminal,
} from "lucide-react";
import type { ReactNode } from "react";
import { baseOptions } from "@/lib/layout.shared";

export const Route = createFileRoute("/")({
  component: Home,
});

type LandingLink = {
  title: string;
  description: string;
  path: string;
  icon: LucideIcon;
};

const proofPoints = [
  {
    title: "Review policy lives in code",
    description:
      "Define reviewers, models, commands, limits, and publication policy in `.pipr/config.ts` so review changes go through pull requests.",
    icon: FileCode2,
  },
  {
    title: "No hosted control plane",
    description:
      "Run Pipr in local development or your CI runner. You don't need a Pipr SaaS account to decide how reviews run.",
    icon: Code2,
  },
  {
    title: "Trusted base config",
    description:
      "Action runs load maintainer-approved config from the base commit, so pull requests cannot rewrite the active reviewer.",
    icon: LockKeyhole,
  },
  {
    title: "Validated comments",
    description:
      "Pipr checks model output against commentable diff ranges before it publishes Main Review Comments or Inline Review Comments.",
    icon: BadgeCheck,
  },
];

const reviewSteps = [
  {
    label: "01",
    title: "Load config",
    description:
      "Read maintainer-approved `.pipr/config.ts` and local imports from the base branch.",
    icon: GitBranch,
  },
  {
    label: "02",
    title: "Model the change",
    description: "Build a deterministic Diff Manifest with files, hunks, and commentable ranges.",
    icon: FileText,
  },
  {
    label: "03",
    title: "Run Pi",
    description: "Execute the Review Task with bounded, read-only change request context.",
    icon: Bot,
  },
  {
    label: "04",
    title: "Validate output",
    description: "Schema-check findings and drop anything that cannot map to a valid range.",
    icon: ShieldCheck,
  },
  {
    label: "05",
    title: "Publish review",
    description: "Write one Main Review Comment and capped Inline Review Comments through GitHub.",
    icon: MessageSquareText,
  },
];

const heroRunSteps = [
  { title: "Config", icon: GitBranch },
  { title: "Diff", icon: FileText },
  { title: "Pi", icon: Bot },
  { title: "Validate", icon: ShieldCheck },
  { title: "Publish", icon: MessageSquareText },
];

const recipeLinks = [
  {
    title: "Default Review",
    description: "General pull request review with bounded inline comments.",
    path: "recipes/default-review",
    icon: MessageSquareText,
  },
  {
    title: "Security SAST",
    description: "Security-focused review with severity and category output.",
    path: "recipes/security-sast",
    icon: ShieldCheck,
  },
  {
    title: "Quality Gate",
    description: "Required check for blocking correctness and test risks.",
    path: "recipes/quality-gate",
    icon: ClipboardCheck,
  },
  {
    title: "Interactive Ask",
    description: "Free-form `@pipr` command over the diff and prior review context.",
    path: "recipes/interactive-ask",
    icon: Bot,
  },
] satisfies LandingLink[];

const maintainerItems = [
  {
    title: "Runs where you run it",
    description:
      "Use the same review policy in local development and GitHub Actions before publishing comments to a pull request.",
    icon: Terminal,
  },
  {
    title: "Secrets stay in env",
    description:
      "`pipr.secret({ name })` stores the variable name in the plan. Provider keys come from runner environment variables.",
    icon: KeyRound,
  },
  {
    title: "GitHub first, provider-neutral core",
    description:
      "GitHub is the first code host adapter. The runtime keeps change request concepts provider-neutral.",
    icon: GitPullRequest,
  },
];

const docsPath = [
  {
    title: "Quickstart",
    description: "Install Pipr and run the first GitHub Action review.",
    path: "guide/quickstart",
    icon: Rocket,
  },
  {
    title: "Guide",
    description: "Configure tasks, entrypoints, comments, trust, and local runs.",
    path: "guide",
    icon: BookOpen,
  },
  {
    title: "Recipes",
    description: "Start from checked-in configs generated by `pipr init --recipe`.",
    path: "recipes",
    icon: CookingPot,
  },
  {
    title: "SDK Reference",
    description: "Look up the TypeScript authoring API for `.pipr/config.ts`.",
    path: "reference/sdk-reference",
    icon: Library,
  },
] satisfies LandingLink[];

function Home() {
  return (
    <HomeLayout {...baseOptions()}>
      <main className="min-h-[calc(100vh-56px)] overflow-hidden bg-fd-background">
        <Hero />
        <WhyPipr />
        <ReviewFlow />
        <RecipesToStartFrom />
        <MaintainerTrust />
        <DocsPath />
      </main>
    </HomeLayout>
  );
}

function Hero() {
  return (
    <section className="overflow-hidden border-b border-fd-border bg-fd-background text-fd-foreground dark:border-pipr-lime/20 dark:bg-pipr-ink dark:text-pipr-cream">
      <div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 sm:py-20 lg:px-8 lg:py-24 xl:grid-cols-[minmax(0,0.95fr)_minmax(420px,0.72fr)] xl:items-center xl:gap-14">
        <div className="max-w-3xl">
          <p className="mb-4 inline-flex items-center gap-2 rounded-md border border-fd-border bg-fd-card px-3 py-1 text-sm font-medium text-fd-primary dark:border-pipr-lime/25 dark:bg-pipr-panel/80 dark:text-pipr-lime">
            <GitPullRequest className="size-4" aria-hidden="true" />
            Code-owned AI review
          </p>
          <h1 className="max-w-4xl text-3xl font-semibold tracking-normal text-fd-foreground sm:text-5xl lg:text-6xl xl:text-[4rem] xl:leading-[1.05] dark:text-pipr-cream">
            Review policy belongs in your repository.
          </h1>
          <p className="mt-6 max-w-2xl text-base leading-7 text-fd-muted-foreground sm:text-lg dark:text-pipr-cream/78">
            Pipr puts AI review policy in `.pipr/config.ts`, runs in local development or CI, and
            publishes only validated GitHub comments. You own the policy, runtime, and publication
            boundary without a hosted Pipr control plane.
          </p>
          <HeroActions />
          <HeroProofStrip />
        </div>
        <HeroReviewScene />
      </div>
    </section>
  );
}

function HeroActions() {
  return (
    <div className="mt-8 flex flex-wrap gap-3">
      <DocsLink
        path="guide/quickstart"
        className="inline-flex items-center gap-2 rounded-lg bg-pipr-lime px-4 py-2.5 text-sm font-medium text-pipr-ink transition-colors hover:bg-pipr-lime/90 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-pipr-lime"
      >
        <Rocket className="size-4" aria-hidden="true" />
        Run the first review
        <ArrowRight className="size-4" aria-hidden="true" />
      </DocsLink>
      <DocsLink
        path="recipes"
        className="inline-flex items-center gap-2 rounded-lg border border-fd-border bg-fd-background px-4 py-2.5 text-sm font-medium text-fd-foreground transition-colors hover:bg-fd-accent focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-fd-ring dark:border-pipr-lime/25 dark:bg-pipr-panel/80 dark:text-pipr-cream dark:hover:border-pipr-lime/45 dark:hover:bg-pipr-lime/10 dark:focus-visible:outline-pipr-lime"
      >
        <CookingPot className="size-4 text-fd-primary dark:text-pipr-lime" aria-hidden="true" />
        Browse recipes
      </DocsLink>
    </div>
  );
}

function HeroProofStrip() {
  return (
    <dl className="mt-10 hidden max-w-2xl gap-3 text-sm text-fd-muted-foreground sm:grid sm:grid-cols-3 dark:text-pipr-cream/72">
      <div>
        <dt className="font-medium text-fd-foreground dark:text-pipr-cream">Config</dt>
        <dd>Policy in repo</dd>
      </div>
      <div>
        <dt className="font-medium text-fd-foreground dark:text-pipr-cream">Runtime</dt>
        <dd>Local or CI runner</dd>
      </div>
      <div>
        <dt className="font-medium text-fd-foreground dark:text-pipr-cream">Output</dt>
        <dd>Validated comments</dd>
      </div>
    </dl>
  );
}

function HeroReviewScene() {
  return (
    <div className="hidden xl:block" data-hero-review-scene aria-hidden="true">
      <div className="rounded-lg border border-fd-border bg-fd-card shadow-xl shadow-black/10 dark:border-pipr-lime/20 dark:bg-pipr-panel/90 dark:shadow-2xl dark:shadow-black/25">
        <HeroConfigPreview />
        <HeroReviewPreview />
      </div>
    </div>
  );
}

function HeroConfigPreview() {
  return (
    <>
      <div className="flex items-center justify-between border-b border-fd-border px-4 py-3 text-xs text-fd-muted-foreground dark:border-pipr-lime/15 dark:text-pipr-cream/62">
        <span className="inline-flex items-center gap-2">
          <Code2 className="size-3.5 text-fd-primary dark:text-pipr-lime" />
          .pipr/config.ts
        </span>
        <span>source of review policy</span>
      </div>
      <pre className="overflow-hidden px-4 py-4 text-[0.76rem] leading-6 text-fd-foreground/80 dark:text-pipr-cream/82">
        <code>{`export default definePipr((pipr) => {
  pipr.review({
    instructions: "Return actionable findings only",
    inlineComments: { max: 5 },
    timeout: "5m",
  });
});`}</code>
      </pre>
    </>
  );
}

function HeroReviewPreview() {
  return (
    <div className="border-t border-fd-border dark:border-pipr-lime/15">
      <HeroReviewHeader />
      <HeroRunRail />
      <HeroReviewOutput />
    </div>
  );
}

function HeroReviewHeader() {
  return (
    <div className="flex items-center justify-between border-b border-fd-border px-4 py-3 dark:border-pipr-lime/15">
      <span className="inline-flex items-center gap-2 text-sm font-medium text-fd-foreground dark:text-pipr-cream">
        <MessageSquareText className="size-4 text-fd-primary dark:text-pipr-lime" />
        Review run
      </span>
      <span className="rounded-md bg-fd-primary/10 px-2 py-1 text-xs text-fd-primary dark:bg-pipr-lime/12 dark:text-pipr-lime">
        validated
      </span>
    </div>
  );
}

function HeroRunRail() {
  return (
    <div className="border-b border-fd-border px-4 py-3 dark:border-pipr-lime/15">
      <div className="grid grid-cols-5 gap-1.5">
        {heroRunSteps.map((step) => (
          <span
            key={step.title}
            className="inline-flex min-w-0 items-center justify-center gap-1 rounded-md border border-fd-border bg-fd-background px-1.5 py-1 text-[0.68rem] font-medium text-fd-muted-foreground dark:border-pipr-lime/20 dark:bg-pipr-lime/5 dark:text-pipr-cream/70"
          >
            <step.icon
              className="size-3 shrink-0 text-fd-primary dark:text-pipr-lime"
              aria-hidden="true"
            />
            {step.title}
          </span>
        ))}
      </div>
    </div>
  );
}

function HeroReviewOutput() {
  return (
    <div className="p-4">
      <div className="rounded-lg border border-fd-border bg-fd-background p-4 dark:border-pipr-lime/20 dark:bg-pipr-ink/45">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs font-medium text-fd-primary dark:text-pipr-lime">
              Published output
            </p>
            <p className="mt-1 text-sm font-medium text-fd-foreground dark:text-pipr-cream">
              Main Review Comment
            </p>
          </div>
          <span className="rounded-md border border-fd-border px-2 py-1 text-xs text-fd-muted-foreground dark:border-pipr-lime/20 dark:text-pipr-cream/62">
            14 files
          </span>
        </div>
        <div className="mt-4 grid grid-cols-3 gap-2">
          <ReviewMetric tone="amber" label="Blocking" value="1" />
          <ReviewMetric tone="cyan" label="Mapped" value="2" />
          <ReviewMetric tone="red" label="Dropped" value="1" />
        </div>
      </div>
    </div>
  );
}

function ReviewMetric({
  tone,
  label,
  value,
}: {
  tone: "amber" | "cyan" | "red";
  label: string;
  value: string;
}) {
  const toneClass = {
    amber: "border-pipr-amber/45 bg-pipr-amber/15",
    cyan: "border-pipr-cyan/45 bg-pipr-cyan/15",
    red: "border-pipr-red/45 bg-pipr-red/10",
  }[tone];

  return (
    <div className={`rounded-md border p-2 ${toneClass}`}>
      <span className="block text-[0.68rem] text-fd-muted-foreground dark:text-pipr-cream/58">
        {label}
      </span>
      <span className="mt-0.5 block text-sm font-medium text-fd-foreground dark:text-pipr-cream">
        {value}
      </span>
    </div>
  );
}

function WhyPipr() {
  return (
    <section className="border-b bg-fd-background">
      <div className="mx-auto max-w-6xl px-6 py-16">
        <SectionHeader
          icon={ShieldCheck}
          eyebrow="Why Pipr"
          title="AI review works when maintainers own the policy."
          description="Opaque review bots ask you to trust policy you cannot version. Pipr keeps the review contract in code, runs where you run it, and validates comments before they reach a pull request."
        />
        <div className="mt-8 grid gap-4 md:grid-cols-2">
          {proofPoints.map((item) => (
            <ProofPoint key={item.title} {...item} />
          ))}
        </div>
      </div>
    </section>
  );
}

function ProofPoint({
  title,
  description,
  icon: Icon,
}: {
  title: string;
  description: string;
  icon: LucideIcon;
}) {
  return (
    <article className="rounded-lg border bg-fd-card p-5">
      <div className="flex items-start gap-4">
        <span className="inline-flex size-10 shrink-0 items-center justify-center rounded-md bg-fd-primary/10 text-fd-primary">
          <Icon className="size-5" aria-hidden="true" />
        </span>
        <div>
          <h3 className="text-base font-medium text-fd-card-foreground">{title}</h3>
          <p className="mt-2 text-sm leading-6 text-fd-muted-foreground">{description}</p>
        </div>
      </div>
    </article>
  );
}

function ReviewFlow() {
  return (
    <section className="border-b bg-fd-muted/35">
      <div className="mx-auto grid max-w-6xl gap-10 px-6 py-16 lg:grid-cols-[0.85fr_1.15fr] lg:items-start">
        <SectionHeader
          icon={ListChecks}
          eyebrow="How review runs work"
          title="From config to comment, every boundary is explicit."
          description="Pipr separates policy loading, diff modeling, Pi execution, validation, and code host publication so maintainers can inspect the review path."
        />
        <div className="rounded-lg border bg-fd-background p-4">
          <ReviewTimeline />
        </div>
      </div>
    </section>
  );
}

function ReviewTimeline({ compact = false }: { compact?: boolean }) {
  const styles = compact ? reviewTimelineStyles.compact : reviewTimelineStyles.default;

  return (
    <ol className={styles.list}>
      {reviewSteps.map((step) => (
        <ReviewTimelineItem key={step.label} step={step} styles={styles} />
      ))}
    </ol>
  );
}

type ReviewTimelineStyles = {
  list: string;
  label: string;
  body: string;
  title: string;
  icon: string;
  description: string;
};

const reviewTimelineStyles = {
  compact: {
    list: "space-y-3",
    label:
      "mt-0.5 inline-flex size-6 shrink-0 items-center justify-center rounded-md border border-pipr-lime/25 bg-pipr-lime/10 text-[0.65rem] font-medium text-pipr-lime",
    body: "text-xs",
    title: "inline-flex items-center gap-2 font-medium text-pipr-cream",
    icon: "size-3.5 text-pipr-lime",
    description: "mt-1 leading-5 text-pipr-cream/58",
  },
  default: {
    list: "space-y-4",
    label:
      "mt-0.5 inline-flex size-9 shrink-0 items-center justify-center rounded-md border bg-fd-card text-xs font-medium text-fd-primary",
    body: "pb-1",
    title: "inline-flex items-center gap-2 font-medium text-fd-foreground",
    icon: "size-4 text-fd-primary",
    description: "mt-1 text-sm leading-6 text-fd-muted-foreground",
  },
} satisfies Record<string, ReviewTimelineStyles>;

function ReviewTimelineItem({
  step,
  styles,
}: {
  step: (typeof reviewSteps)[number];
  styles: ReviewTimelineStyles;
}) {
  return (
    <li className="flex gap-3">
      <span className={styles.label}>{step.label}</span>
      <div className={styles.body}>
        <p className={styles.title}>
          <step.icon className={styles.icon} aria-hidden="true" />
          {step.title}
        </p>
        <p className={styles.description}>{step.description}</p>
      </div>
    </li>
  );
}

function RecipesToStartFrom() {
  return (
    <section className="border-b bg-fd-background">
      <div className="mx-auto max-w-6xl px-6 py-16">
        <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between">
          <SectionHeader
            icon={CookingPot}
            eyebrow="Recipes to start from"
            title="Starter configs for common review workflows."
            description="Each recipe page shows the install command, generated files, code, and when to use the workflow."
          />
          <DocsLink
            path="recipes"
            className="inline-flex w-fit items-center gap-2 rounded-lg border bg-fd-background px-4 py-2.5 text-sm font-medium text-fd-foreground transition-colors hover:bg-fd-accent"
          >
            View all recipes
            <ArrowRight className="size-4" aria-hidden="true" />
          </DocsLink>
        </div>
        <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {recipeLinks.map((recipe) => (
            <RecipeCTA key={recipe.path} {...recipe} />
          ))}
        </div>
      </div>
    </section>
  );
}

function RecipeCTA({
  title,
  description,
  path,
  icon: Icon,
}: {
  title: string;
  description: string;
  path: string;
  icon: LucideIcon;
}) {
  return (
    <DocsLink
      path={path}
      className="group rounded-lg border bg-fd-card p-5 transition-colors hover:bg-fd-accent"
    >
      <span className="mb-4 inline-flex size-9 items-center justify-center rounded-md bg-fd-primary/10 text-fd-primary">
        <Icon className="size-4" aria-hidden="true" />
      </span>
      <h3 className="text-base font-medium text-fd-card-foreground">{title}</h3>
      <p className="mt-2 text-sm leading-6 text-fd-muted-foreground">{description}</p>
      <span className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-fd-primary">
        Open recipe
        <ArrowRight
          className="size-4 transition-transform group-hover:translate-x-0.5"
          aria-hidden="true"
        />
      </span>
    </DocsLink>
  );
}

function MaintainerTrust() {
  return (
    <section className="border-b bg-pipr-ink text-pipr-cream">
      <div className="mx-auto grid max-w-6xl gap-10 px-6 py-16 lg:grid-cols-[0.8fr_1.2fr] lg:items-start">
        <SectionHeader
          icon={KeyRound}
          eyebrow="Built for maintainers"
          title="No hosted Pipr control plane."
          description="Pipr reads provider keys from your runner environment, keeps model choice in repository-owned config, and publishes through the code host adapter you run."
          dark
        />
        <div className="grid gap-4 md:grid-cols-3">
          {maintainerItems.map((item) => (
            <article
              key={item.title}
              className="rounded-lg border border-pipr-lime/20 bg-pipr-panel p-5"
            >
              <item.icon className="size-5 text-pipr-lime" aria-hidden="true" />
              <h3 className="mt-4 text-base font-medium text-pipr-cream">{item.title}</h3>
              <p className="mt-2 text-sm leading-6 text-pipr-cream/68">{item.description}</p>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}

function DocsPath() {
  return (
    <section className="bg-fd-background">
      <div className="mx-auto max-w-6xl px-6 py-16">
        <SectionHeader
          icon={BookOpen}
          eyebrow="Docs path"
          title="Install it, then tune it like code."
          description="Start with the first review, use recipes for common policies, and move into SDK APIs when the repository needs more control."
        />
        <div className="mt-8 grid gap-4 md:grid-cols-2">
          {docsPath.map((item) => (
            <DocsPathLink key={item.path} {...item} />
          ))}
        </div>
      </div>
    </section>
  );
}

function DocsPathLink({
  title,
  description,
  path,
  icon: Icon,
}: {
  title: string;
  description: string;
  path: string;
  icon: LucideIcon;
}) {
  return (
    <DocsLink
      path={path}
      className="flex items-start gap-4 rounded-lg border bg-fd-card p-5 transition-colors hover:bg-fd-accent"
    >
      <span className="inline-flex size-10 shrink-0 items-center justify-center rounded-md bg-fd-primary/10 text-fd-primary">
        <Icon className="size-5" aria-hidden="true" />
      </span>
      <span>
        <span className="block text-base font-medium text-fd-card-foreground">{title}</span>
        <span className="mt-2 block text-sm leading-6 text-fd-muted-foreground">{description}</span>
      </span>
    </DocsLink>
  );
}

function SectionHeader({
  icon: Icon,
  eyebrow,
  title,
  description,
  dark = false,
}: {
  icon: LucideIcon;
  eyebrow: string;
  title: string;
  description: string;
  dark?: boolean;
}) {
  return (
    <div className="max-w-2xl">
      <p
        className={
          dark
            ? "mb-3 inline-flex items-center gap-2 text-sm font-medium text-pipr-lime"
            : "mb-3 inline-flex items-center gap-2 text-sm font-medium text-fd-primary"
        }
      >
        <Icon className="size-4" aria-hidden="true" />
        {eyebrow}
      </p>
      <h2
        className={
          dark
            ? "text-2xl font-semibold tracking-normal text-pipr-cream sm:text-3xl"
            : "text-2xl font-semibold tracking-normal text-fd-foreground sm:text-3xl"
        }
      >
        {title}
      </h2>
      <p
        className={
          dark
            ? "mt-3 text-sm leading-6 text-pipr-cream/68"
            : "mt-3 text-sm leading-6 text-fd-muted-foreground"
        }
      >
        {description}
      </p>
    </div>
  );
}

function DocsLink({
  path,
  className,
  children,
}: {
  path: string;
  className?: string;
  children: ReactNode;
}) {
  return (
    <Link
      to="/docs/$"
      params={{
        _splat: path,
      }}
      className={className}
    >
      {children}
    </Link>
  );
}
