apiVersion: pipr.dev/v1
kind: CommandSet
id: pipr/default-commands
description: Default pipr pull request commands.
commands:
  - id: review
    aliases:
      - "@pipr review"
    run:
      workflows:
        - pipr/review
  - id: summary
    aliases:
      - "@pipr summary"
    run:
      workflows:
        - pipr/review
  - id: help
    aliases:
      - "@pipr help"
    run:
      block: core/show-help
